### PR TITLE
[Fixes #99239564] Explicitly declare type returned by getJava() 

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz

### CODE REVIEW

**Comment by jimlloyd** [comment]
Merging pending review.

**Comment by mhfrantz** [comment]
It looks like we DO have `--noImplicitAny` set, so it's curious that we were able to get away with an undeclared exported function return type.

**Comment by mhfrantz** [comment]
LGTM

**Comment by jimlloyd** [comment]
As I said in my comment just above, it looks to me that the compiler didn't the return type an implicit `any`, but rather as an implicit more specific type: `typeof _java`. Then, when the .d.ts file was generated, it turned that `typeof _java` into an explicit, but unexported type.

**Pull request merged**
