### PR TITLE
Exclude anonymous classes in whitelist filtering

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz Replaces #3.

### CODE REVIEW

**Comment by jimlloyd** [comment]
Github is showing the commits out of order due to rebasing. Logically, this PR does this:
1) Add the new .java classes necessary to produce an anonymous class.
2) Add a new BDD feature that specifies the desired behavior, but fails since anon classes are not filtered.
3) Exclude anon classes in whitelist filter, which fixes the failing BDD test.

**Comment by mhfrantz** [comment]
FTP

No changes required, but let me know if you want to do anything based on my observations.

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
LGTM pending Travis

**Pull request merged**
