### PR TITLE
[Delivers #93039890] ts-java composability

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz This is a major refactoring, and is a monster of a PR. I believe most of the 46 commits are small enough to be easily reviewed, but at least a couple (flagged as 'Big bang: ...') that possibly should have been broken into smaller commits.

The 'autoImport' function was adapted to serve the new primary method of generating 'tsJavaModules'. The name change autoImport -> tsJavaModule doesn't happen until near the end of the PR.

The updated README is in the last commit -- you might want to look at it first.

### CODE REVIEW

**Comment by mhfrantz** [comment]
I find myself looking at those generated TS files and wondering which Java namespaces are contained inside.  I wonder if the ts-java options should be splatted in a header comment.

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
The suggestion to splat the tsjava options into the generated file is a good one. I'll make that change and fix the other nits/typos tomorrow.

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
LGTM

**Pull request merged**
