### PR TITLE
[Delivers #88266836] Tighter semantics on package expresssions

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz

### CODE REVIEW

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

I revised featureset/package.json to use the package expression  `com.redseal.featureset.**`. This includes the nested package `com.redseal.featureset.ambiguous`, which has the class `com.redseal.featureset.ambiguous.Thing` that is used in the BDD scenarios.

**Comment by mhfrantz** [comment]
OK, now we have coverage of the recursive package spec, but not verification that the non-recursive package spec will properly include nested classes in that package.

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
Added BDD tests.
PTAL

**Comment by jimlloyd** [comment]
Build failure was due to api.github rate limiting. The `Update tsd.json` commit should fix that problem.
PTAL

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
LGTM pending Travis

**Comment by jimlloyd** [comment]
Travis green

**Pull request merged**
