### PR TITLE
[Delivers #99755374 #100051132] Add debug output in generated tsJavaModules

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz 

Also includes #100051132: Expose .class in .Static interfaces

### CODE REVIEW

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL. 
And of course, due to all the !fixup commits, don't merge, I will rebase.

**Comment by mhfrantz** [comment]
LGTM rebase

**Comment by jimlloyd** [comment]
Replaced by #18

**Pull request closed without merging**
