### PR TITLE
Resolve subtle difference in class inheritance models between java and typescript

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz.

### CODE REVIEW

**Comment by mhfrantz** [comment]
The work queue feels somewhat like a wheel.  Can you compare/contrast to the `async` library, or to the Bluebird API that deals with collections of futures?

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
I suppose there might be some very clever way to use promises instead of my Work queue concept, but I doubt very much that it would result in easier to understand code. I don't want to do any of this processing in parallel. I know that I have to process a large set of classes, and at the beginning of the processing I only know their class names. During processing, I discover their inheritance relationship, and as I do, I need to suspend work on a child class until its parents are all processed.

If you want the algorithm to be easier to understand, I could make one pass over all of the classes to create an inheritance DAG, and then do the processing on that DAG in breadth first search starting from java.lang.Object.

But to do that, I'd have to create new data structures for the DAG. It would be a significant rewrite, for very little benefit.

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
OK, it took me another look to understand how work was being used.  No change necessary.

**Comment by jimlloyd** [comment]
I broke the unit tests, despite testing with `make unittest`. I'll have to fix this after dinner.

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
LGTM

**Pull request merged**
